// @ts-check
// prettier-ignore
module.exports = /** @type TProduct[] */ ([
  {
    extra: '<div class="le-ribbon blue right"><span>New!</span></div>',
    image: '/vendor/images/products/products-real/real-x300.png',
    priceOld: 250,
    price: 145,
    stars: 3,
    name: 'consectetur adipiscing elit - extra_long_text_line_for_testing_purposes_only',
    excerpt: 'Looking lorem round, to ascertain that they - extra_long_text_line_for_testing_purposes_only.',
  },
  {
    image: '/vendor/images/products/products-modelist-1/product02.png',
    priceOld: 350,
    price: 245,
    stars: 4,
    name: 'Man sport Hiking shoe',
    excerpt: 'Looking lorem round, to ascertain that they...',
  },
  {
    extra: '<div class="le-badge orange"><span>50% off</span></div>',
    image: '/vendor/images/products/products-modelist-1/product03.png',
    priceOld: 450,
    price: 245,
    stars: 4,
    name: 'Woman highheel shoe',
    excerpt: 'Looking lorem round, to ascertain that they...',
  },
  {
    extra: '<div class="le-badge green"><span>New</span></div>',
    image: '/vendor/images/products/products-modelist-1/product04.png',
    priceOld: 120,
    price: 95,
    stars: 2,
    name: 'colorful cool runnig shoes',
    excerpt: 'Looking lorem round, to ascertain that they...',
  },
  {
    image: '/vendor/images/products/products-modelist-1/product03.png',
    priceOld: 450,
    price: 245,
    stars: 4,
    name: 'Woman highheel shoe',
    excerpt: 'Looking lorem round, to ascertain that they...',
  },
  {
    image: '/vendor/images/products/products-modelist-1/product02.png',
    priceOld: 0,
    price: 245,
    stars: 4,
    name: 'Man sport Hiking shoe',
    excerpt: 'Looking lorem round, to ascertain that they...',
  },
  {
    image: '/vendor/images/products/products-modelist-1/product04.png',
    priceOld: 0,
    price: 95,
    stars: 2,
    name: 'colorful cool runnig shoes',
    excerpt: 'Looking lorem round, to ascertain that they...',
  },
  {
    image: '/vendor/images/products/products-modelist-1/product01.png',
    priceOld: 0,
    price: 145,
    stars: 3,
    name: 'consectetur adipiscing elit',
    excerpt: 'Looking lorem round, to ascertain that they...',
  },
]);
