---
  baseURL: 'https://emboss.studio'
  author: 'emboss.studio'
  description: 'VR/360 platform for group online tours'
  title: 'emboss.studio - VR/360 platform for group online tours'
  language: 'en'
  mainSitePrefix: 'https://emboss.studio/private'
  test: 'XXX'
  social:
    -
      title: 'Twitter'
      url: 'https://twitter.com/#'
    -
      title: 'LinkedIn'
      url: 'https://linkedin.com/company/#'

