---
  baseURL: 'https://emboss.studio'
  author: 'emboss.studio'
  description: 'Site description'
  title: 'emboss.studio - Brief site name'
  language: 'en'
  mainSitePrefix: 'https://emboss.studio'
  test: 'Test'
  social:
    -
      title: 'Twitter'
      url: 'https://twitter.com/#'
    -
      title: 'LinkedIn'
      url: 'https://linkedin.com/company/#'

